// <auto-generated />
using DogBreed.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DogBreed.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DogBreed.Models.DogBreed", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Breed")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubBreed")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DogBreeds");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Breed = "affenpinscher"
                        },
                        new
                        {
                            Id = 2,
                            Breed = "african"
                        },
                        new
                        {
                            Id = 3,
                            Breed = "airedale"
                        },
                        new
                        {
                            Id = 4,
                            Breed = "akita"
                        },
                        new
                        {
                            Id = 5,
                            Breed = "appenzeller"
                        },
                        new
                        {
                            Id = 6,
                            Breed = "basenji"
                        },
                        new
                        {
                            Id = 7,
                            Breed = "beagle"
                        },
                        new
                        {
                            Id = 8,
                            Breed = "bluetick"
                        },
                        new
                        {
                            Id = 9,
                            Breed = "borzoi"
                        },
                        new
                        {
                            Id = 10,
                            Breed = "bouvier"
                        },
                        new
                        {
                            Id = 11,
                            Breed = "boxer"
                        },
                        new
                        {
                            Id = 12,
                            Breed = "brabancon"
                        },
                        new
                        {
                            Id = 13,
                            Breed = "briard"
                        },
                        new
                        {
                            Id = 14,
                            Breed = "bulldog",
                            SubBreed = "\r\n  boston,\r\n  french\r\n"
                        },
                        new
                        {
                            Id = 15,
                            Breed = "bullterrier",
                            SubBreed = "\r\n  staffordshire\r\n"
                        },
                        new
                        {
                            Id = 16,
                            Breed = "cairn"
                        },
                        new
                        {
                            Id = 17,
                            Breed = "chihuahua"
                        },
                        new
                        {
                            Id = 18,
                            Breed = "chow"
                        },
                        new
                        {
                            Id = 19,
                            Breed = "clumber"
                        },
                        new
                        {
                            Id = 20,
                            Breed = "collie",
                            SubBreed = "\r\n  border\r\n"
                        },
                        new
                        {
                            Id = 21,
                            Breed = "corgi",
                            SubBreed = "\r\n  cardigan\r\n"
                        },
                        new
                        {
                            Id = 22,
                            Breed = "dachshund"
                        },
                        new
                        {
                            Id = 23,
                            Breed = "dane",
                            SubBreed = "\r\n  great\r\n"
                        },
                        new
                        {
                            Id = 24,
                            Breed = "deerhound",
                            SubBreed = "\r\n  scottish\r\n"
                        },
                        new
                        {
                            Id = 25,
                            Breed = "dhole"
                        },
                        new
                        {
                            Id = 26,
                            Breed = "dingo"
                        },
                        new
                        {
                            Id = 27,
                            Breed = "doberman"
                        },
                        new
                        {
                            Id = 28,
                            Breed = "elkhound",
                            SubBreed = "\r\n  norwegian\r\n"
                        },
                        new
                        {
                            Id = 29,
                            Breed = "entlebucher"
                        },
                        new
                        {
                            Id = 30,
                            Breed = "eskimo"
                        },
                        new
                        {
                            Id = 31,
                            Breed = "germanshepherd"
                        },
                        new
                        {
                            Id = 32,
                            Breed = "greyhound",
                            SubBreed = "\r\n  italian\r\n"
                        },
                        new
                        {
                            Id = 33,
                            Breed = "groenendael"
                        },
                        new
                        {
                            Id = 34,
                            Breed = "hound",
                            SubBreed = "\r\n  Ibizan,\r\n  afghan,\r\n  basset,\r\n  blood,\r\n  english,\r\n  walker\r\n"
                        },
                        new
                        {
                            Id = 35,
                            Breed = "husky"
                        },
                        new
                        {
                            Id = 36,
                            Breed = "keeshond"
                        },
                        new
                        {
                            Id = 37,
                            Breed = "kelpie"
                        },
                        new
                        {
                            Id = 38,
                            Breed = "komondor"
                        },
                        new
                        {
                            Id = 39,
                            Breed = "kuvasz"
                        },
                        new
                        {
                            Id = 40,
                            Breed = "labrador"
                        },
                        new
                        {
                            Id = 41,
                            Breed = "leonberg"
                        },
                        new
                        {
                            Id = 42,
                            Breed = "lhasa"
                        },
                        new
                        {
                            Id = 43,
                            Breed = "malamute"
                        },
                        new
                        {
                            Id = 44,
                            Breed = "malinois"
                        },
                        new
                        {
                            Id = 45,
                            Breed = "maltese"
                        },
                        new
                        {
                            Id = 46,
                            Breed = "mastiff",
                            SubBreed = "\r\n  bull,\r\n  tibetan\r\n"
                        },
                        new
                        {
                            Id = 47,
                            Breed = "mexicanhairless"
                        },
                        new
                        {
                            Id = 48,
                            Breed = "mountain",
                            SubBreed = "\r\n  bernese,\r\n  swiss\r\n"
                        },
                        new
                        {
                            Id = 49,
                            Breed = "newfoundland"
                        },
                        new
                        {
                            Id = 50,
                            Breed = "otterhound"
                        },
                        new
                        {
                            Id = 51,
                            Breed = "papillon"
                        },
                        new
                        {
                            Id = 52,
                            Breed = "pekinese"
                        },
                        new
                        {
                            Id = 53,
                            Breed = "pembroke"
                        },
                        new
                        {
                            Id = 54,
                            Breed = "pinscher",
                            SubBreed = "\r\n  miniature\r\n"
                        },
                        new
                        {
                            Id = 55,
                            Breed = "pointer",
                            SubBreed = "\r\n  german\r\n"
                        },
                        new
                        {
                            Id = 56,
                            Breed = "pomeranian"
                        },
                        new
                        {
                            Id = 57,
                            Breed = "poodle",
                            SubBreed = "\r\n  miniature,\r\n  standard,\r\n  toy\r\n"
                        },
                        new
                        {
                            Id = 58,
                            Breed = "pug"
                        },
                        new
                        {
                            Id = 59,
                            Breed = "pyrenees"
                        },
                        new
                        {
                            Id = 60,
                            Breed = "redbone"
                        },
                        new
                        {
                            Id = 61,
                            Breed = "retriever",
                            SubBreed = "\r\n  chesapeake,\r\n  curly,\r\n  flatcoated,\r\n  golden\r\n"
                        },
                        new
                        {
                            Id = 62,
                            Breed = "ridgeback",
                            SubBreed = "\r\n  rhodesian\r\n"
                        },
                        new
                        {
                            Id = 63,
                            Breed = "rottweiler"
                        },
                        new
                        {
                            Id = 64,
                            Breed = "saluki"
                        },
                        new
                        {
                            Id = 65,
                            Breed = "samoyed"
                        },
                        new
                        {
                            Id = 66,
                            Breed = "schipperke"
                        },
                        new
                        {
                            Id = 67,
                            Breed = "schnauzer",
                            SubBreed = "\r\n  giant,\r\n  miniature\r\n"
                        },
                        new
                        {
                            Id = 68,
                            Breed = "setter",
                            SubBreed = "\r\n  english,\r\n  gordon,\r\n  irish\r\n"
                        },
                        new
                        {
                            Id = 69,
                            Breed = "sheepdog",
                            SubBreed = "\r\n  english,\r\n  shetland\r\n"
                        },
                        new
                        {
                            Id = 70,
                            Breed = "shiba"
                        },
                        new
                        {
                            Id = 71,
                            Breed = "shihtzu"
                        },
                        new
                        {
                            Id = 72,
                            Breed = "spaniel",
                            SubBreed = "\r\n  blenheim,\r\n  brittany,\r\n  cocker,\r\n  irish,\r\n  japanese,\r\n  sussex,\r\n  welsh\r\n"
                        },
                        new
                        {
                            Id = 73,
                            Breed = "springer",
                            SubBreed = "\r\n  english\r\n"
                        },
                        new
                        {
                            Id = 74,
                            Breed = "stbernard"
                        },
                        new
                        {
                            Id = 75,
                            Breed = "terrier",
                            SubBreed = "\r\n  american,\r\n  australian,\r\n  bedlington,\r\n  border,\r\n  dandie,\r\n  fox,\r\n  irish,\r\n  kerryblue,\r\n  lakeland,\r\n  norfolk,\r\n  norwich,\r\n  patterdale,\r\n  scottish,\r\n  sealyham,\r\n  silky,\r\n  tibetan,\r\n  toy,\r\n  westhighland,\r\n  wheaten,\r\n  yorkshire\r\n"
                        },
                        new
                        {
                            Id = 76,
                            Breed = "vizsla"
                        },
                        new
                        {
                            Id = 77,
                            Breed = "weimaraner"
                        },
                        new
                        {
                            Id = 78,
                            Breed = "whippet"
                        },
                        new
                        {
                            Id = 79,
                            Breed = "wolfhound",
                            SubBreed = "\r\n  irish\r\n"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
